name: Deploy
on:
  - push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          mkdir build
          chmod 777 build
          docker run --rm -v $PWD:/opt -w /opt -e USER_ID=$UID ddidier/sphinx-doc:7.1.2-1 sphinx-build -b html source build

      - name: Install AWS Cli
        run: pip install awscli

      - name: Deploy to AWS
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1
        run: |
          aws s3 sync build \
          s3://clrhs-prod-nonpci-docs-3dsecure-io/3dsv2 --delete
          aws cloudfront create-invalidation --distribution-id E7TJBG3FUU0TD --paths '/3dsv2/*'

      - name: Deploy to AWS - Dry-run
        if: ${{ github.ref != 'refs/heads/master' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1
        run: |
          aws s3 sync build \
          s3://clrhs-prod-nonpci-docs-3dsecure-io/3dsv2 --dryrun --delete
